version: '3.8'

services:
  db-main:
    image: postgres:14.7-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - '5433:5432'
    volumes:
      - db-main:/var/lib/postgresql/data
  pathmaker-api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 80
    ports:
      - 5024:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - db-main
volumes:
  db-main:
    driver: local
