name: Deploy - Web

on:
  push:
    branches: 
      - main
    paths:
      - web/**
    
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_KEY}}
            heroku_app_name: pathmaker
            heroku_email: morasiu2@gmail.com
            usedocker: true
            appdir: web
