name: CI Pipeline

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build API
      run: dotnet build

    - name: Test API
      run: dotnet test --no-build --verbosity normal

  build-app:
    runs-on: ubuntu-latest
    needs: build-api
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build --if-present

    - name: Test app
      run: vitest

    - name: Lint app
      run: npm run lint

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-app
    defaults:
      run:
        working-directory: ./e2e

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install Playwright
      run: |
        npm install -g playwright
        playwright install

    - name: Install Reqnroll
      run: dotnet tool install -g Reqnroll.Tool

    - name: Build E2E tests
      run: dotnet build

    - name: Run E2E tests
      run: dotnet test --no-build --verbosity normal
