version: '3.8'

services:
  db-main:
    image: postgres:14.7-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - '5433:5432'
    volumes:
      - db-main:/var/lib/postgresql/data
  pathmaker-api:
    build: 
      context: ../api/Pathmaker
      dockerfile: Dockerfile
    ports:
      - 5024:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - db-main
  pathmaker-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - pathmaker-api
volumes:
  db-main:
    driver: local